### ISSUE TITLE
你好 想问一下项目打包环境需要自己配置吗？

### ISSUE THREAD

**Issue by zhufeiyao-admin** [zhangyuge7/five-admin-v2#3]
打包的时候没有看到正式和测试环境
![image](https://github.com/user-attachments/assets/3551611d-b305-40ef-a431-3f9b56c7d1eb)

**Comment by zhangyuge7** [comment]
执行`build`默认使用`.env.production`，执行`dev`默认使用`.env.development`
![image](https://github.com/user-attachments/assets/6816fe73-773a-4ef8-8d31-0d14f2c98e1b)
